### ISSUE TITLE
Couldn't get prisma client models, make sure you are using Prisma v5 or above.

### ISSUE THREAD

**Issue by simonKristensen** [premieroctet/next-crud#64]
Hi, I've started getting this error recently. I am using Prisma 5.8.1.

```
 ⨯ Error: Couldn't get prisma client models, make sure you are using Prisma v5 or above.
    at PrismaAdapter.getPrismaClientModels (/home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/adapters/prisma/index.js:34:19)
    at PrismaExtendedAdapter.<anonymous> (/home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/adapters/prisma/index.js:44:43)
    at Generator.next (<anonymous>)
    at /home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/adapters/prisma/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/adapters/prisma/index.js:4:12)
    at PrismaExtendedAdapter.init (/home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/adapters/prisma/index.js:42:16)
    at /home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/handler.js:40:76
    at Generator.next (<anonymous>)
    at /home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/handler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/handler.js:4:12)
    at NextCrud (/home/user/path_to_project/node_modules/@premieroctet/next-crud/dist/handler.js:29:12)
    at handler (webpack-internal:///(api)/./pages/api/[...nextcrud].ts:54:81) {
```

Any idea what else could be the cause?

I am using a custom Prisma adapter to scope some user access to various entities, but I haven't touched it for many months, and the above error only recently appeared.

I cannot recall if I recently updated any other packages sorry, but from what I can tell, it looks like the issue is something related to dmmf not being defined in the PrismaAdapter constructor?
(It happens at `node_modules/@premieroctet/next-crud/dist/adapters/prisma/index.js` line 34
``` javascript
class PrismaAdapter {
    constructor({ primaryKey = 'id', prismaClient, manyRelations = {}, models, }) {
        this.getPrismaClientModels = () => {
            if (client_1.Prisma.dmmf) {
                // @ts-ignore
                this.dmmf = client_1.Prisma.dmmf;
                return client_1.Prisma.dmmf.datamodel.models.map((m) => m.name);
            }
/// THIS LINE ///
            throw new Error("Couldn't get prisma client models, make sure you are using Prisma v5 or above.");
/// THIS LINE ///
        };
        this.prismaClient = prismaClient;
        this.primaryKey = primaryKey;
        this.manyRelations = manyRelations;
        this._ctorModels = models;
    }
```

Any hints would be greatly appreciated! :pray:

**Comment by simonKristensen** [comment]
Hmm, still don't know what happened - but running `yarn upgrade --latest` seems to have fixed it regardless.
